# .github/workflows/ci.yml
name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: pip install pytest pytest-cov mypy ruff bandit
      - run: pytest --cov=app/safety --cov-report=term-missing -q
      - run: mypy app/safety/safety.py
      - run: ruff check .
      - run: bandit -q -r app
